[tool.isort]
line_length = 119
force_single_line = true
known_third_party = ["launch"]
src_paths = ["."]

[tool.flake8]
aggressive = 2
ignore = "W503, ANN002, ANN003, ANN1, D104, C801"
max-line-length = 119
select = "E,F,W,C,N,I,D,ANN,T"
copyright-check = true
copyright-regexp = "# Copyright (c) [0-9]{4} SoftBank Corp.\n#\n# Licensed under the Apache License, Version 2.0 (the \"License\");\n# you may not use this file except in compliance with the License.\n# You may obtain a copy of the License at\n#\n#     http://www.apache.org/licenses/LICENSE-2.0\n#\n# Unless required by applicable law or agreed to in writing, software\n# distributed under the License is distributed on an \"AS IS\" BASIS,\n# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n# See the License for the specific language governing permissions and\n# limitations under the License."
docstring-convention = "google"
suppress-dummy-args = true

[tool.autopep8]
max_line_length = 119
ignore = "W503"
aggressive = 2

[tool.yapf]
based_on_style = "pep8"
column_limit = 119
DEDENT_CLOSING_BRACKETS = false
SPLIT_BEFORE_ARITHMETIC_OPERATOR = true

[tool.ruff]
src = ["src", "."]
line-length = 119
select = ["ANN", "E", "F", "I", "N", "W", "D", "T", "CPY", "Q"]
ignore = ["ANN002", "ANN003", "ANN1"]

[tool.ruff.flake8-quotes]
inline-quotes = "single"

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.flake8-copyright]
notice-rgx = "# Copyright (c) [0-9]{4} SoftBank Corp.\n#\n# Licensed under the Apache License, Version 2.0 (the \"License\");\n# you may not use this file except in compliance with the License.\n# You may obtain a copy of the License at\n#\n#     http://www.apache.org/licenses/LICENSE-2.0\n#\n# Unless required by applicable law or agreed to in writing, software\n# distributed under the License is distributed on an \"AS IS\" BASIS,\n# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n# See the License for the specific language governing permissions and\n# limitations under the License."

[tool.ruff.isort]
known-third-party = ["launch"]
force-single-line = true

[tool.ruff.flake8-annotations]
suppress-dummy-args = true

[tool.ruff.format]
quote-style = "single"
line-ending = "lf"
