"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#333333)\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
[](#333333)\
$line_break\
$character\
$line_break"""
right_format = """$azure\
$gcloud\
$aws\
$terraform\
$container\
$nodejs\
$rust\
$python\
$time"""

[username]
format = "[$user]($style)"
style_root = "yellow bg:#333333"
style_user = "yellow bg:#333333"

[hostname]
format = "[$ssh_symbol$hostname]($style)"
style = "yellow bg:#333333"

[character]
success_symbol = "[❯](green)"
error_symbol = "[✘](red)"

[directory]
format = '[ $path]($style)[$read_only ]($read_only_style)'
truncation_length = 1000
style = "bright-blue bg:#333333"
read_only_style = "red bg:#333333"
truncate_to_repo = false

[time]
disabled = false
format = "[$time]($style) "
style = "white"

[git_branch]
format = "[$symbol$branch(:$remote_branch) ]($style)"
style = "green bg:#333333"
symbol = "  "

[git_commit]
format = '[$hash$tag ]($style)'
style = "green bg:#333333"
tag_disabled = false

[git_state]
style = "red bg:#333333"
format = '[$state( $progress_current/$progress_total) ]($style)'

[git_status]
format = """([$ahead_behind$conflicted$stashed$renamed$staged]($style)\
[$deleted$modified](yellow bg:#333333)\
[$untracked](bright-blue bg:#333333))"""
style = 'green bg:#333333'
stashed = '󰶌 ${count} '
ahead = '⇡${count} '
behind = '⇣${count} '
up_to_date = ''
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
conflicted = '=${count} '
deleted = '✘${count} '
renamed = '»${count} '
modified = '!${count} '
staged = '+${count} '
untracked = '?${count} '

[cmd_duration]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[python]
disabled = false
format = '[${symbol}${version}($virtualenv) ](bright-blue)'
python_binary = ['./venv/bin/python', 'python', 'python3']
symbol = ' '

[package]
disabled = true
